name: cols100_n2
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - streamlit
  - numpy
  - pandas
  - ipywidgets
  - plotly
  - glob2
  - tabulate
  - nbconvert
  - wxpython
  - pandoc
